// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	game "github.com/viniciusfal/placar/internal/domain/game"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// BuscarPorID provides a mock function with given fields: ctx, id
func (_m *MockRepository) BuscarPorID(ctx context.Context, id string) (*game.Game, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for BuscarPorID")
	}

	var r0 *game.Game
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*game.Game, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *game.Game); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*game.Game)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_BuscarPorID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuscarPorID'
type MockRepository_BuscarPorID_Call struct {
	*mock.Call
}

// BuscarPorID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) BuscarPorID(ctx interface{}, id interface{}) *MockRepository_BuscarPorID_Call {
	return &MockRepository_BuscarPorID_Call{Call: _e.mock.On("BuscarPorID", ctx, id)}
}

func (_c *MockRepository_BuscarPorID_Call) Run(run func(ctx context.Context, id string)) *MockRepository_BuscarPorID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_BuscarPorID_Call) Return(_a0 *game.Game, _a1 error) *MockRepository_BuscarPorID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_BuscarPorID_Call) RunAndReturn(run func(context.Context, string) (*game.Game, error)) *MockRepository_BuscarPorID_Call {
	_c.Call.Return(run)
	return _c
}

// Salvar provides a mock function with given fields: ctx, g
func (_m *MockRepository) Salvar(ctx context.Context, g *game.Game) error {
	ret := _m.Called(ctx, g)

	if len(ret) == 0 {
		panic("no return value specified for Salvar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *game.Game) error); ok {
		r0 = rf(ctx, g)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Salvar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Salvar'
type MockRepository_Salvar_Call struct {
	*mock.Call
}

// Salvar is a helper method to define mock.On call
//   - ctx context.Context
//   - g *game.Game
func (_e *MockRepository_Expecter) Salvar(ctx interface{}, g interface{}) *MockRepository_Salvar_Call {
	return &MockRepository_Salvar_Call{Call: _e.mock.On("Salvar", ctx, g)}
}

func (_c *MockRepository_Salvar_Call) Run(run func(ctx context.Context, g *game.Game)) *MockRepository_Salvar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*game.Game))
	})
	return _c
}

func (_c *MockRepository_Salvar_Call) Return(_a0 error) *MockRepository_Salvar_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Salvar_Call) RunAndReturn(run func(context.Context, *game.Game) error) *MockRepository_Salvar_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
